import { StyleSheet } from "react-native";

export default StyleSheet.create({
  container: {
    backgroundColor: "white",
    flexDirection: "column",
  },
  altSubmitText: {
    fontSize: 18,
    paddingTop: 10,
    textTransform: "uppercase",
    color: "white",
  },
  loadingContainer: {
    flex: 1,
    backgroundColor: "white",
    alignItems: "center",
    justifyContent: "center",
    fontSize: 16,
    color: "#2f4f4f",
  },
  keyBar: {
    flexDirection: "row",
    justifyContent: "space-between",
    borderColor: "#2f4f4f",
    borderRadius: 15,
    borderWidth: 2,
    height: 55,
    alignContent: "center",
    alignItems: "center",
    paddingHorizontal: 20,
    paddingVertical: 5,
    marginTop: 20,
  },
  submitText: {
    fontSize: 18,
    paddingTop: 10,
    textTransform: "uppercase",
    color: "#2f4f4f",
  },
  centered: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 20,
  },
  button: {
    // flex: 1,
    backgroundColor: "#f50",
    alignItems: "center",
    justifyContent: "center",
    marginTop: 50,
  },
  baseText: {
    paddingBottom: 20,
    fontSize: 16,
  },
  listText: {
    paddingBottom: 5,
    fontSize: 16,
  },
  titleText: {
    fontSize: 20,
    fontWeight: "bold",
    paddingTop: 40,
    paddingBottom: 10,
    color: "#2f4f4f",
  },
  bodyTitleText: {
    fontSize: 20,
    fontWeight: "bold",
    paddingTop: 20,
    paddingBottom: 10,
    color: "#2f4f4f",
  },
  card: {
    width: "100%",
    flexDirection: "row",
    paddingHorizontal: 20,
    elevation: 5,
    justifyContent: "center",
    alignItems: "center",
    alignContent: "center",
    height: 50,
  },
  input: {
    paddingVertical: 6,
    backgroundColor: "white",
    paddingHorizontal: 20,
    color: "#2f4f4f",
    marginVertical: 12,
    width: "100%",
    height: 55,
    overflow: "scroll",
    borderRadius: 15,
    marginBottom: 10,
    fontSize: 16,
  },
  altTitleText: {
    fontSize: 20,
    fontWeight: "bold",
    paddingTop: 30,
    paddingBottom: 20,
    color: "white",
  },
  subTitleText: {
    fontSize: 18,
    fontWeight: "bold",
    paddingVertical: 10,
    color: "#2f4f4f",
  },
});
