import { StyleSheet } from "react-native";

export default StyleSheet.create({
  container: {
    backgroundColor: "#fff",
    flexDirection: "column",
  },
  iconAndText: {
    alignItems: "center",
    paddingVertical: 16,
    marginVertical: 10,
    flexDirection: "row",
    justifyContent: "center",
    borderRadius: 32,
    shadowRadius: 32,
    color: "white",
    backgroundColor: "#2f4f4f",
  },

  titleText: {
    fontSize: 20,
    color: "#2f4f4f",
    fontWeight: "bold",
    paddingTop: 30,
    paddingBottom: 10,
  },
  centeredView: {
    alignItems: "center",
    borderColor: "#2f4f4f",
    borderRadius: 15,
    borderWidth: 3,

    paddingVertical: 12,
    paddingHorizontal: 20,

    height: 55,
    overflow: "scroll",
    fontSize: 16,
    textAlign: "center",
  },

  disabledCenteredView: {
    alignItems: "center",

    paddingHorizontal: 20,
    height: 55,
    overflow: "scroll",
    fontSize: 16,
    textAlign: "center",
  },
  modalView: {
    margin: 60,
    backgroundColor: "white",
    borderRadius: 20,
    padding: 35,
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
  },
  button: {
    borderRadius: 15,
    paddingVertical: 10,
    paddingHorizontal: 15,
    elevation: 2,
  },
  buttonClose: {
    backgroundColor: "#2f4f4f",
    marginTop: 15,
  },
  textStyle: {
    color: "white",
    textAlign: "center",
  },
  modalText: {
    marginBottom: 15,
    textAlign: "center",
  },

  formContainer: {
    paddingHorizontal: 40,
  },
  formText: {
    fontSize: 20,
    color: "white",
  },
  new: {
    color: "white",
  },
  image: {
    flex: 1,
    resizeMode: "cover",
    justifyContent: "center",
  },
  bodyImage: {
    marginTop: 40,
    flex: 1,
    resizeMode: "cover",
    justifyContent: "center",
  },
  gif: {
    width: 55,
    height: 55,
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
  },
  newGif: {
    width: 55,
    height: 55,
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 15,
    marginLeft: 10,
  },
  gifBackground: {
    flexDirection: "column",
    marginTop: 40,
    paddingVertical: 15,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#2f4f4f",
  },
  buttonBackground: {
    flexDirection: "column",
    paddingBottom: 15,
    alignItems: "center",
    justifyContent: "center",
  },
  disabledButtonBackground: {
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
  },
  loginText: {
    flexDirection: "column",
    alignItems: "center",
    paddingTop: 2,
    justifyContent: "center",
    marginVertical: 10,
  },
  end: {
    flexDirection: "column",

    alignItems: "center",
    paddingTop: 2,
    justifyContent: "center",
  },
  baseText: {
    fontSize: 16,
  },
  cardText: {
    fontSize: 16,
    fontWeight: "bold",
  },
  cardTextEmphasized: {
    fontSize: 16,
    fontStyle: "italic",
  },
  baseTextEmphasizedDisabled: {
    fontSize: 16,
    fontStyle: "italic",
    color: "white",
  },
  pressableText: {
    textTransform: "uppercase",
    fontWeight: "bold",
    paddingBottom: 40,
    color: "#2f4f4f",
  },
  disabledText: {
    textTransform: "uppercase",
    fontStyle: "italic",
    paddingTop: 14,
    fontWeight: "bold",
    color: "gray",
  },
  loginText: {
    fontSize: 22,
    color: "white",
  },
  disabledCard: {
    width: "100%",
    flexDirection: "row",
    marginVertical: 8,
    borderRadius: 15,
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderColor: "#2f4f4f",
    color: "white",
    backgroundColor: "rgba(47, 79, 79, 0.15)",
    borderWidth: 4,
    elevation: 5,
    justifyContent: "space-between",
    alignItems: "center",
    alignContent: "center",
    height: 85,
  },
  card: {
    width: "100%",
    flexDirection: "row",
    marginVertical: 8,
    borderRadius: 15,
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderColor: "#2f4f4f",
    borderWidth: 4,
    elevation: 5,
    justifyContent: "space-between",
    alignItems: "center",
    alignContent: "center",
    height: 85,
  },
  iconContainer: {
    shadowColor: "#2f4f4f",
    flexDirection: "row",
    alignItems: "center",
    marginLeft: 14,
    justifyContent: "center",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.8,
    shadowRadius: 1,
  },
  signupText: {
    fontSize: 20,
    fontStyle: "italic",
    color: "white",
  },
  titleText: {
    fontSize: 20,
    fontWeight: "bold",
    paddingTop: 40,
    paddingBottom: 10,
    color: "#2f4f4f",
  },
  bareTitleText: {
    fontSize: 20,
    fontWeight: "bold",
    paddingBottom: 10,
    color: "#2f4f4f",
  },
  searchBar: {
    flexDirection: "row",
    justifyContent: "space-between",
    borderColor: "#2f4f4f",
    borderRadius: 15,
    borderWidth: 2,
    height: 55,
    alignContent: "center",
    alignItems: "center",
    paddingHorizontal: 20,
    paddingVertical: 5,
    backgroundColor: "#2f4f4f",
    marginVertical: 40,
  },

  input: {
    paddingVertical: 6,
    color: "white",
    paddingHorizontal: 20,
    marginVertical: 12,
    width: "100%",
    height: 55,
    overflow: "scroll",
    borderRadius: 15,
    marginBottom: 30,
    fontSize: 16,
  },
});
